steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$TAG_NAME', '-f', 'Dockerfile-development','--cache-from','us-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$TAG_NAME','.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$TAG_NAME' ]
  # Deploy container image to Cloud Run

  # Configuración de Costa Rica
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'demo-spring-gcp-cloud-run-dev'
      - '--image'
      - 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/github-containers/demo-spring-gcp-cloud-run:$TAG_NAME'
      - '--region'
      - 'us-central1'
      - '--set-env-vars'
      - 'PROPERTY_FILE=development'
images:
  - 'us-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$TAG_NAME'