steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$COMMIT_SHA', '-f', 'Dockerfile-production', '--cache-from','us-central1-docker.pkg
    .dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$COMMIT_SHA','.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$COMMIT_SHA' ]
  # Deploy container image to Cloud Run

  # Configuración de Costa Rica
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'demo-spring-gcp-cloud-run-cr'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--set-env-vars'
      - 'PROPERTY_FILE=production'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/github-containers/demo-spring-gcp-cloud-run:$COMMIT_SHA'